"""
SignalScope — Media Authenticity Detector
Clean Neo-Brutalist Single-Page Interface
Simple, human-friendly language • Clear visual hierarchy • Zero emojis
"""
import sys
from pathlib import Path

# Ensure project root is in sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import io
import zipfile
import pandas as pd
import streamlit as st
from PIL import Image

from app.services.analysis_service import AnalysisService
from app.components.verdict_card import render_verdict_card
from app.components.heatmap_viewer import render_heatmap_viewer
from app.components.spectrum_plot import render_spectrum_plots
from app.components.metadata_panel import render_metadata_panel

# 1. Page Configuration (No sidebar, wide screen)
st.set_page_config(
    page_title="SignalScope — Real vs AI Image Checker",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# 2. Inject Clean Neo-Brutalist CSS
css_path = Path(__file__).parent / "assets" / "custom.css"
if css_path.exists():
    with open(css_path, "r", encoding="utf-8") as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

# 3. Service
@st.cache_resource
def get_analysis_service():
    return AnalysisService()

service = get_analysis_service()

# 4. Header / Brand Hero
st.markdown(
    """
    <div class="brand-hero">
      <div class="brand-hero-title">
        <svg viewBox="0 0 100 100" class="brand-star-icon">
          <path d="M50 0 C50 35 65 50 100 50 C65 50 50 65 50 100 C50 65 35 50 0 50 C35 50 50 35 50 0 Z"/>
        </svg>
        <span>SignalScope</span>
      </div>
      <p class="brand-hero-subtitle">
        Drop any image below to check whether it was taken with a real camera or generated by AI.
      </p>
    </div>
    """,
    unsafe_allow_html=True,
)

# 5. STEP 1: Choose Image
st.markdown(
    """
    <div class="clean-card" style="padding: 20px 24px; margin-bottom: 16px;">
      <div style="font-weight: 800; font-size: 1.15rem; margin-bottom: 8px;">
        Step 1: Choose an Image to Inspect
      </div>
      <div style="font-size: 0.92rem; color: #555555; margin-bottom: 14px;">
        Upload your own image or click one of the test samples below to see how it works immediately:
      </div>
    </div>
    """,
    unsafe_allow_html=True,
)

sample_col1, sample_col2, sample_col3 = st.columns(3)
sample_to_load = None

with sample_col1:
    if st.button("Try Sample: AI Generated Image", use_container_width=True):
        sample_to_load = "data/samples/sample_synthetic_diffusion.png"
with sample_col2:
    if st.button("Try Sample: Real Camera Photo", use_container_width=True):
        sample_to_load = "data/samples/sample_camera_authentic.jpg"
with sample_col3:
    if st.button("Try Sample: C2PA Signed Image", use_container_width=True):
        sample_to_load = "data/samples/sample_c2pa_firefly.jpg"

uploaded_file = st.file_uploader(
    "Or upload your own image file (JPG, PNG, WebP):",
    type=["jpg", "jpeg", "png", "webp"],
    help="Select an image from your computer to run forensics.",
)

active_bytes = None
active_filename = "sample.jpg"

if sample_to_load and Path(sample_to_load).exists():
    with open(sample_to_load, "rb") as f:
        active_bytes = f.read()
    active_filename = Path(sample_to_load).name
    st.session_state["active_bytes"] = active_bytes
    st.session_state["active_filename"] = active_filename
elif uploaded_file is not None:
    active_bytes = uploaded_file.getvalue()
    active_filename = uploaded_file.name
    st.session_state["active_bytes"] = active_bytes
    st.session_state["active_filename"] = active_filename
elif "active_bytes" in st.session_state:
    active_bytes = st.session_state["active_bytes"]
    active_filename = st.session_state.get("active_filename", "sample.jpg")

# 6. STEP 2: Results & Inspection
if active_bytes:
    with st.spinner("Analyzing image patterns, camera traces, and metadata..."):
        analysis = service.analyze_image(active_bytes, filename=active_filename, use_tta=False)
        pil_img = Image.open(io.BytesIO(active_bytes)).convert("RGB")

    st.markdown(
        """
        <div style="font-weight: 800; font-size: 1.25rem; margin: 28px 0 14px 0; color: #080808;">
          Step 2: Analysis Results
        </div>
        """,
        unsafe_allow_html=True,
    )

    # Top Row: Verdict Summary Card
    render_verdict_card(analysis.verdict, analysis.generator_family, analysis.processing_time_ms)

    # Main Diagnostic Grid
    col_left, col_right = st.columns([1, 1], gap="large")

    with col_left:
        st.markdown(
            f"""
            <div class="clean-card">
              <div class="clean-card-header">
                <span>Selected Image: {analysis.filename}</span>
                <span style="font-size: 0.85rem; color: #777;">{analysis.image_size[0]} x {analysis.image_size[1]} px</span>
              </div>
            </div>
            """,
            unsafe_allow_html=True,
        )
        st.image(pil_img, caption="Analyzed Image", use_container_width=True)

        # Interactive Heatmap View
        if analysis.heatmap_array is not None:
            st.markdown('<div class="clean-card">', unsafe_allow_html=True)
            render_heatmap_viewer(pil_img, analysis.heatmap_array)
            st.markdown("</div>", unsafe_allow_html=True)

    with col_right:
        # Key Evidence Breakdown
        st.markdown(
            """
            <div class="clean-card">
              <div class="clean-card-header">
                <span>Key Evidence Found</span>
              </div>
            """,
            unsafe_allow_html=True,
        )

        for cue in analysis.cues:
            bar_color = "#FF3B30" if cue.severity == "high" else ("#FFCC00" if cue.severity == "medium" else "#00D722")
            st.markdown(
                f"""
                <div class="evidence-item" style="border-left-color: {bar_color};">
                  <div class="evidence-title">{cue.cue_type} ({cue.confidence * 100:.0f}% confidence)</div>
                  <div class="evidence-desc">{cue.description}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )

        st.markdown("</div>", unsafe_allow_html=True)

        # Camera & Digital Signature Info
        st.markdown('<div class="clean-card">', unsafe_allow_html=True)
        render_metadata_panel(analysis.metadata)
        st.markdown("</div>", unsafe_allow_html=True)

    # Deeper Frequency & Sensor Analysis (Clean expandable section)
    with st.expander("Show Deep Signal & Sensor Analysis (Frequency, JPEG Compression, Bayer Sensor)"):
        st.markdown('<div class="clean-card" style="margin-top: 10px;">', unsafe_allow_html=True)
        render_spectrum_plots(analysis.spectral)
        st.markdown("</div>", unsafe_allow_html=True)

else:
    st.markdown(
        """
        <div class="clean-card" style="text-align: center; padding: 40px 20px;">
          <div style="font-weight: 700; font-size: 1.1rem; margin-bottom: 8px;">Waiting for an image...</div>
          <div style="color: #666; font-size: 0.95rem;">
            Click one of the three sample buttons above, or drag and drop an image file to start.
          </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

# 7. STEP 3: Batch Scanner Section (Clean at the bottom)
st.markdown("---")
st.markdown(
    """
    <div style="font-weight: 800; font-size: 1.25rem; margin: 20px 0 10px 0; color: #080808;">
      Need to Check Multiple Images at Once?
    </div>
    """,
    unsafe_allow_html=True,
)

with st.expander("Open Batch Scanner (Multiple Files or ZIP Archive)"):
    batch_uploads = st.file_uploader(
        "Upload multiple images or a ZIP file containing images:",
        type=["jpg", "jpeg", "png", "webp", "zip"],
        accept_multiple_files=True,
        key="batch_uploader",
    )

    batch_items = []
    if batch_uploads:
        for uf in batch_uploads:
            if uf.name.lower().endswith(".zip"):
                try:
                    with zipfile.ZipFile(io.BytesIO(uf.getvalue())) as z:
                        for zname in z.namelist():
                            if zname.lower().endswith((".jpg", ".jpeg", ".png", ".webp")) and not zname.startswith("__MACOSX"):
                                batch_items.append((Path(zname).name, z.read(zname)))
                except Exception as e:
                    st.error(f"Could not read ZIP archive: {e}")
            else:
                batch_items.append((uf.name, uf.getvalue()))

    if batch_items:
        st.write(f"Ready to scan **{len(batch_items)}** images.")

        if st.button("Start Batch Scan Now", type="primary"):
            p_bar = st.progress(0, text="Scanning images...")
            ledger = []

            for idx, (fname, fbytes) in enumerate(batch_items):
                p_bar.progress((idx + 1) / len(batch_items), text=f"Scanning {idx+1}/{len(batch_items)}: {fname}")
                item_res = service.analyze_image(fbytes, filename=fname)
                ledger.append({
                    "Filename": item_res.filename,
                    "Verdict": item_res.verdict.label,
                    "Certainty": f"{item_res.verdict.confidence * 100:.1f}%",
                    "Likely Source": item_res.generator_family,
                    "Camera Info Found": "Yes" if item_res.metadata.has_exif else "No",
                    "C2PA Signed": item_res.metadata.c2pa_status,
                    "Anomalies": len(item_res.metadata.anomalies),
                })

            p_bar.empty()
            df = pd.DataFrame(ledger)

            ai_hits = sum(1 for r in ledger if "AI" in r["Verdict"])
            real_hits = sum(1 for r in ledger if "Authentic" in r["Verdict"] or "Real" in r["Verdict"])
            uncertain_hits = len(ledger) - ai_hits - real_hits

            m1, m2, m3 = st.columns(3)
            with m1:
                st.metric("Total Scanned", len(ledger))
            with m2:
                st.metric("Flagged as AI", ai_hits)
            with m3:
                st.metric("Verified Real", real_hits)

            st.dataframe(df, use_container_width=True)

            csv_data = df.to_csv(index=False).encode("utf-8")
            st.download_button(
                label="Download Results as CSV",
                data=csv_data,
                file_name="signalscope_scan_results.csv",
                mime="text/csv",
                use_container_width=True,
            )

# 8. Clean Simple Footer
st.markdown(
    """
    <div style="margin-top: 50px; padding-top: 18px; border-top: 2px solid #080808; display: flex; justify-content: space-between; font-size: 0.82rem; color: #222222; font-weight: 600;">
      <div>SignalScope Media Authenticity Platform</div>
      <div>Powered by DINOv2, SRM Noise Analysis, and C2PA Verification</div>
    </div>
    """,
    unsafe_allow_html=True,
)
